config/routes.rb
Rss::Application.routes.draw do

  devise_for :users

  resources :subscriptions

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match '/about', to: 'static_pages#about'

  root :to => 'home#index'

end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
	attr_accessible :guid, :name, :published_at, :summary, :url, :feed_url
	validates_presence_of :guid, :published_at, :url, :feed_url

	def self.update_all_feeds_continuously(delay_interval = 10.minutes)
		feed_urls = Subscription.pluck("DISTINCT location")
		feeds = Feedzirra::Feed.fetch_and_parse(feed_urls)
		feeds.each { |k, f| add_entries(f.entries, k) unless f == 0 }
		loop do

			# add/remove feeds
			new_feeds = Subscription.pluck("DISTINCT location")
			if new_feeds != feed_urls
				new_feeds.each do |url|
					if feeds[url] == nil
						feeds.merge!( url => Feedzirra::Feed.fetch_and_parse(url) )
					end
				end

				feed_urls.each do |url|
					unless new_feeds.include?(url)
						feeds.except!(url)
					end
				end
				feed_urls = new_feeds
			end

			#feeds = Feedzirra::Feed.fetch_and_parse(feed_urls)
			feeds.each do |k, f| 
				if f = []
					f = Feedzirra::Feed.fetch_and_parse(k)
					add_entries(f.entries, k)
				end

				updated = Feedzirra::Feed.update(f)
				unless updated == nil 
					add_entries(updated.entries, k)
				end
			end

		end

		# since Feedzirra update fails on feeds with no etags,
		# we'll have to do this weird manual thing
		# perhaps this can be solved one day

		# old code
		#update existing feeds
		#updated = Feedzirra::Feed.update(feeds.values)
		#
		#if updated != nil
		#	feeds = updated
		#	feeds.each do |f| 
		#		add_entries(f.new_entries, f.feed_url) if f.updated?
		#	end
	end

def self.addSubscription(location)
	feed = Feedzirra::Feed.fetch_and_parse(location)
	if feed != 0 && feed != nil
		add_entries(feed.entries, location)
		return true
	else
		return false
	end
end

def self.removeSubscription(location)
	# this is mainly a cleanup method
	# new feeds of the name won't be collected
	# so we just remove old entries
	destroy_all(:feed_url => location)
end

private

def self.add_entries(entries, feed_url)
	entries.each do |entry|
		unless exists? :guid => entry.id
			create!(
				:name         => entry.title,
				:summary      => entry.summary ? entry.summary : entry.content,
				:url          => entry.url,
				:published_at => entry.published,
				:feed_url     => feed_url,
				:guid         => entry.id
			)
		end
	end
end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  attr_accessible :last, :location
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :rememberable, :registerable #:database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
	attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
	has_many :subscriptions

	def self.from_omniauth(auth)
		where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.name
			user.oauth_token = auth.credentials.token
			user.oauth_expires_at = Time.at(auth.credentials.expires_at)
			user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to root_url
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

	def index
	end

	def show	
		if user_signed_in?
			begin
			@subscription = Subscription.find(params[:id])
			@subscription = nil unless @subscription.user_id == current_user.id
			rescue
			end
		end
	end

	def create
		newsub = Subscription.new(params[:subscription])
		insert = true
		current_user.subscriptions.each { |sub|
			insert = false if sub.location == newsub.location
		}

		if insert
			if FeedEntry.addSubscription(newsub.location)
				@subscription = current_user.subscriptions.create(params[:subscription])
				render 'index'
			else
				flash[:notice] = 'URL contains no entries.'
				render 'index'
			end
		else
			flash[:notice] = 'You are already subscribed to this URL.'
			render 'index'
		end
	end

	def destroy
		sub = Subscription.find(params[:id])
		if sub.user_id == current_user.id
			sub.destroy
			FeedEntry.removeSubscription(sub.location) if Subscription.where(location: sub.location) == []
		end

		redirect_to subscriptions_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# return full title on per-page basis
	def full_title(page_title)
		base_title = "rsstful"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
	<h1>Feeds</h1>
	<% if current_user.subscriptions.empty? %>
		<p> You are currently not subscribed to any feeds. Would you like to <%= link_to "add some?", subscriptions_path %></p>
	<% else %>
		<% current_user.subscriptions.each do |sub| %>
			<h2><%= sub.location %></h2>
			<% FeedEntry.order("published_at DESC").limit(3).where(:feed_url => sub.location).each do |f| %>
				<div id="feeddisplay">
					<h3><%= link_to f.name, f.url %></h3>
					<p><%= f.published_at %></p>
					<p><%= f.summary.html_safe %></p>
				</div>                                          
			<% end %>
		<% end %>
	<% end %>

<% else %>
	<%= render 'layouts/loggedout' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
	(c) 2013 <a href="http://ut.ee/~mudkip">Karl Puusepp</a>
</small>
<nav>
<ul>
	<li><%= link_to "About",   'about' %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
	<div class="container">
		<%= link_to "rsstful", '/', id: "logo" %>
		<nav>
		<ul class="nav pull-right">
			<li>
			<div id="user_nav">
				<% if current_user %>
					welcome, <strong><%= current_user.name %></strong> |
					<%= link_to "subscriptions", subscriptions_path, id: "sign_out" %> |
					<%= link_to "logout", signout_path, id: "sign_out" %> 
				<% else %>
					<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
				<% end %>
			</div>
			</li>
		</ul>
		</nav>
	</div>
</div>
</header>

app/views/layouts/_loggedout.html.erb
<div id="openingcrawl">
	<h2> <strong>rss</strong>tful is a simple and beautiful RSS reader. <%= link_to "Log on board!", "/auth/facebook" %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'about') %>
<h1>About</h1>
<p>rsstful is a school project for a Ruby on Rails course written and developed by Karl Puusepp.
It's source code is publicly available at http://github.com/rerelease/rsstful</p>

app/views/subscriptions/index.html.erb
<% if user_signed_in? %>
	<h2> Add a subscription</h2>
	<% if notice %>
		<p id="notice" ><%= notice %></p> 
	<% end %>
	<%= form_for(:subscription) do |f| %>
		<p>
		<%= f.label :location %><br />
		<%= f.text_field :location %>
		</p>
		<p>
		<%= f.submit %>
		</p>
	<% end %>

	<h2> My subscriptions </h2>

	<table>
		<tr>
			<th>URL</th>
			<th>Text</th>
			<th></th>
			<th></th>
		</tr>

		<% current_user.subscriptions.each do |sub| %>
			<tr>
				<td><%= sub.location %></td>
				<td><%= sub.created_at %></td>
				<td><%= link_to 'Show', subscription_path(sub) %></td>
				<td><%= link_to 'Unsubscribe', subscription_path(sub), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<% provide(:title, 'please log in') %>
	<%= render 'layouts/loggedout' %>
<% end %>

app/views/subscriptions/show.html.erb
<% if user_signed_in? %>
	<% unless @subscription == nil %>
		<p>
		<strong>Feed at: </strong><%= @subscription.location %>
		</p>

		<% FeedEntry.where(:feed_url => @subscription.location).each do |f| %>
			<div id="feeddisplay">
				<h3><%= link_to f.name, f.url %></h3>
				<p><%= f.published_at %></p>
				<p><%= f.summary.html_safe %></p>
			</div>
		<% end %>

	<% else %>
		<h2>You shouldn't be here.</h2>
	<%end%>
<% else %>
	<%= render 'layouts/loggedout' %>
<% end %>